const resList = [
  {
    type: "ticket",
    data: {
      type: "Art",
      id: "12345",
      date: " OCT 10",
      time: "Mon, 7.30 PM",
      name: "Morgan Jay",
      category: ["Art", "Theater"],
      description: "Laugh Out Loud Comedy Club",
      place: "San Antonio, TX",
      cost: 4000,
      img: "img1.jpg",
    },
  },
  {
    type: "ticket",
    data: {
      type: "Art",
      id: "123409",
      date: " OCT 11",
      time: "Tue, 4.30 PM",
      name: "Revolver Comedy with Raul Sanchez",
      category: ["Art", "Theater"],
      description: "Laugh Out Loud Comedy Club",
      place: "San Antonio, TX",
      cost: 1500,
      img: "img2.jpg",
    },
  },
  {
    type: "ticket",
    data: {
      type: "Art",
      id: "1234511",
      date: " OCT 11",
      time: "Wed, 5.30 PM",
      name: "Tina Fey & Amy Poehler: Restless Leg Tour",
      category: ["Art", "Theater"],
      description: "Bass Concert Hall",
      place: "Austin, TX",
      cost: 2000,
      img: "img3.jpg",
    },
  },
  {
    type: "ticket",
    data: {
      type: "Art",
      id: "12349009",
      date: " OCT 13",
      time: "Thu, 10.30 PM",
      name: "Beauty And The Beast w/ Ballet San Antonio",
      category: ["Art", "Theater"],
      description: "H-E-B Performance Hall",
      place: "San Antonio, TX",
      cost: 1000,
      img: "img1.jpg",
    },
  },
  {
    type: "ticket",
    data: {
      type: "Art",
      id: "12345112",
      date: " OCT 10",
      time: "Fri, 7.30 PM",
      name: "Tina Fey & Amy Poehler: Restless Leg Tour",
      category: ["Art", "Theater"],
      description: "Bass Concert Hall",
      place: "Austin, TX",
      cost: 2000,
      img: "img1.jpg",
    },
  },
];

export default resList;
